image_width: 320
image_height: 240
camera_name: rpi_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [673.66435,   0.     , 142.52516,
           0.     , 677.38725,  67.01383,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.096484, 0.456241, -0.031448, -0.008844, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [680.32794,   0.     , 141.35862,   0.     ,
           0.     , 676.51062,  64.53681,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
