image_width: 320
image_height: 180
camera_name: rpi_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [423.11905,   0.     , 158.2191 ,
           0.     , 211.56345,  89.49967,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.131576, -0.065836, 0.002045, 0.001946, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [436.80728,   0.     , 158.21515,   0.     ,
           0.     , 217.84154,  89.28157,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
